services:
  - type: web
    name: mi-api-dotnet
    runtime: docker
    repo: https://github.com/SergioRdzMndz/backend_pvm.git 
    branch: main
    plan: free
    dockerfilePath: ./Back/Dockerfile 
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: PORT
        value: 8080
